os:
    - linux

language: julia

julia:
    - 1.0
    - 1
    - nightly

notifications:
    email: false

git:
    depth: 99999

after_success:
    - julia --color=yes --project=test/coverage/ -e 'using Pkg; Pkg.add("ForwardDiff"); Pkg.instantiate()'
    - julia --color=yes --project=test/coverage/ test/coverage/coverage.jl


jobs:
  include:
    - stage: deploy
      if: branch = master
      julia: 1
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.add("Documenter");Pkg.add("ForwardDiff"); Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
        - julia --color=yes --project=test/coverage/ -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=test/coverage/ test/coverage/coverage.jl

