export
   fast_trilinear_earth_interpolate,
   fast_tricubic_earth_interpolate,
   fast_tricubic_earth_interpolate_gradient,
   fast_tricubic_earth_interpolate_eqvari,
   sshVelocityRHS,
   read_ocean_velocities,
   read_ssh,
   getP
