export
   uv_trilinear,
   uv_tricubic,
   uv_quadlinear,
   ssh_tricubic,
   ssh_tricubic_gradient,
   uv_tricubic_eqvari,
   sshVelocityRHS,
   read_ocean_velocities,
   read_ssh,
   getPFull,
   getPPart
